# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babyblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(max_length=70),
        ),
    ]
