# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babyblog', '0003_auto_20161114_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='tweet_user',
            new_name='tweet_creator',
        ),
    ]
